# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AelyQsxRXnvYwwACOt_NO8yfe1E4nTcg
"""

import numpy as np

def alpha_to_num(text):
    message = []
    for i in text:
        if i.isupper():
            number = ord(i) - 65
            message.append(number)
        elif i.islower():
            number = ord(i) - 97
            message.append(number)
    return message

def array_div(message):
    message = np.array(message)
    new_message = message.reshape(-1, 2).T
    return new_message

def cipher_text(new_message, key):
    c = np.dot(key, new_message) % 26
    return c

if __name__ == "__main__":
    key_input = input("Enter the Key (4 integers separated by spaces): ")
    key = np.array(key_input.split(), dtype=int).reshape(2, 2)

    plaintext = input("Enter the text to be encrypted: ")

    a = alpha_to_num(plaintext)
    b = array_div(a)
    c = cipher_text(b, key)

    print("Cipher Text:", c.T)



m= np.array([[1,3],[5,6]])
new_message = m.reshape(-1,2).T
new_message

